-- AlterTable
ALTER TABLE "pets" ALTER COLUMN "id_owner" SET DATA TYPE TEXT,
ALTER COLUMN "gender" SET DATA TYPE TEXT,
ALTER COLUMN "height" SET DATA TYPE TEXT,
ALTER COLUMN "animal" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "cp" SET DATA TYPE TEXT,
ALTER COLUMN "number_int" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "veterinarys" ALTER COLUMN "number_int" SET DATA TYPE TEXT,
ALTER COLUMN "cp" SET DATA TYPE TEXT;
